### ISSUE TITLE
Implement Paul's Suggestions

### ISSUE THREAD

**Issue by kand198** [uoa-ypec413/metacodenition#86]
- [x] problem page: change "next question" button to "next test case" button
- [x] test on all browsers
- [x] fix auto generate comments - make it go to the correct line
- [x] move programming experience question to end, remove gender etc. 
- [x] add initialization to test cases
- [ ] ~add gifs / videos~

**Comment by kand198** [comment]
For #4, I have completely removed the beginning questionnaire. @uoa-ypec413 do you think we still need to ask students to assess their own programming competence or can we just look at their performance on Q1 (the question done in CodeRunner and not Metacodenition).

**Comment by uoa-ypec413** [comment]
> For #4, I have completely removed the beginning questionnaire in #87. @uoa-ypec413 do you think we still need to ask students to assess their own programming competence or can we just look at their performance on Q1 (the question done in CodeRunner and not Metacodenition).

Assessing their own competence is easier for us, because we don't need to pull in data from another source. 
What I'm worried about with performance on Q1 is whether it'd actually be valuable info for us. My concerns are:
1. Q1 is usually a really easy question, and I'd assume that most students would do well if they just listened to the lecture. Would there even be a visible difference in performance?
2. How do we measure performance when they have unlimited attempts to get the question correct? Do we only take their first attempt into account?

**Comment by uoa-ypec413** [comment]
I feel like info on students' grades in the Matlab portion or even on the last lab's hardest question could be more valuable?

**Comment by kand198** [comment]
Checking off item 2 for now, as everything seems to work on firefox (webkit based) and we've developed on chrome. therefore we should be compatible with pretty much every browser.

**Comment by kand198** [comment]
Scratched off item 6 (last item) as it has its own tickets
